services:
  mlh-portfolio:
    container_name: mlh-portfolio
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - db
  db:
    container_name: mlh-portfolio-db
    image: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=3030
      - MYSQL_USER=lovinson
      - MYSQL_PASSWORD=01302004
      - MYSQL_DATABASE=myportfoliodb
    volumes:
      - mydatabase:/var/lib/mysql

  nginx:
    container_name: mlh-portfolio-nginx
    image: jonasal/nginx-certbot
    restart: always
    environment:
      - CERTBOT_EMAIL=name@gmail.com
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - mlh-portfolio

volumes:
  mydatabase:
  nginx_secrets:
