name: Run tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    env:
      TESTING: true
      URL: localhost:5000
      MYSQL_HOST: localhost
      MYSQL_USER: lovinson
      MYSQL_PASSWORD: 01302004
      MYSQL_DATABASE: myportfoliodb
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Setup Python Virtual Environment
        run: python -m venv python3-virtualenv

      - name: Install dependencies
        run: python3-virtualenv/bin/pip install -r requirements.txt

      - name: Install python env
        run: pip install python-dotenv

      - name: Make run_test.sh executable
        run: chmod +x ./run_test.sh

      - name: Run tests
        run: ./run_test.sh
  deploy:
    name: "Deploy to VPS"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY " > ~/.ssh/MLH-Key.pem
          chmod 600 ~/.ssh/MLH-Key.pem
          cat >> ~/.ssh/config << END
          Host my-vps
            HostName $SSH_IP
            User $SSH_USER
            IdentityFile ~/.ssh/MLH-Key.pem
            StrictHostKeyChecking no
          END
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_IP: ${{ secrets.SSH_IP }}
          SSH_USER: ${{ secrets.SSH_USER }}

      - name: Deploy to VPS
        run: ssh my-vps 'cd ${{ secrets.SSH_PRIVATE_KEY}} && git pull'
