name: Run tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    env:
      TESTING: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Setup Python Virtual Environment
        run: python -m venv python3-virtualenv

      - name: Install dependencies
        run: python3-virtualenv/bin/pip install -r requirements.txt

      - name: Install python env
        run: pip install python-dotenv

      - name: Make run_test.sh executable
        run: chmod +x ./run_test.sh

      - name: Run tests
        run: ./run_test.sh
